CREATE DATABASE IF NOT EXISTS todo_db;
USE todo_db;


CREATE TABLE IF NOT EXISTS users(
  user_id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(50) UNIQUE NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  names VARCHAR(100) NOT NULL,
  surnames VARCHAR(100) DEFAULT NULL,
  gender ENUM('M', 'F') DEFAULT NULL,
  birth_date DATE DEFAULT NULL,
  join_date DATE DEFAULT CURRENT_TIMESTAMP,
  password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  status ENUM('pending', 'completed') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);